from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import (
    StringField, PasswordField, SelectField, SelectMultipleField,
    TextAreaField, BooleanField, IntegerField, DateField, HiddenField, TimeField,
)
from wtforms.validators import DataRequired, Email, Length, EqualTo, Optional, NumberRange

DEPARTMENTS = [
    ("", "— Select department —"),
    ("ACCOUNTING", "ACCOUNTING"),
    ("ACCOUNTING (EMT)", "ACCOUNTING (EMT)"),
    ("Accounting (DIPLOMA)", "Accounting (DIPLOMA)"),
    ("DEPARTMENT (PART-TIME)", "DEPARTMENT (PART-TIME)"),
    ("ACCOUNTING EDUCATION (SANDWICH)", "ACCOUNTING EDUCATION (SANDWICH)"),
    ("EDUCATION", "EDUCATION"),
    ("ACTUARIAL SCIENCE", "ACTUARIAL SCIENCE"),
    ("ACTUARIAL SCIENCE (PART-TIME)", "ACTUARIAL SCIENCE (PART-TIME)"),
    ("ADULT EDUCATION (HUMAN KINETICS) (SANDWICH)", "ADULT EDUCATION (HUMAN KINETICS) (SANDWICH)"),
    ("ADULT EDUCATION", "ADULT EDUCATION"),
    ("DEVELOPMENT", "DEVELOPMENT"),
    ("ADULT EDUCATION/ ACCOUNTING", "ADULT EDUCATION/ ACCOUNTING"),
    ("ADULT EDUCATION/ CHRISTAIN RELGIOUS STUDIES", "ADULT EDUCATION/ CHRISTAIN RELGIOUS STUDIES"),
    ("ADULT EDUCATION/ COMMUNITY DEVELOPMENT", "ADULT EDUCATION/ COMMUNITY DEVELOPMENT"),
    ("ADULT EDUCATION/ ECONOMICS", "ADULT EDUCATION/ ECONOMICS"),
    ("ADULT EDUCATION/ ENGLISH", "ADULT EDUCATION/ ENGLISH"),
    ("ADULT EDUCATION/ FRENCH", "ADULT EDUCATION/ FRENCH"),
    ("ADULT EDUCATION/ GEOGRAPHY", "ADULT EDUCATION/ GEOGRAPHY"),
    ("ADULT EDUCATION/ HISTORY", "ADULT EDUCATION/ HISTORY"),
    ("ADULT EDUCATION/ INDUSTRIAL AND LABOUR STUDIES", "ADULT EDUCATION/ INDUSTRIAL AND LABOUR STUDIES"),
    ("ADULT EDUCATION/ POLITICAL SCIENCE", "ADULT EDUCATION/ POLITICAL SCIENCE"),
    ("ADULT EDUCATION/ SOCIAL STUDIES", "ADULT EDUCATION/ SOCIAL STUDIES"),
    ("ADULT EDUCATION/ WOMEN EDUCATION", "ADULT EDUCATION/ WOMEN EDUCATION"),
    ("ADULT EDUCATION/ COOPERATIVE MANAGEMENT", "ADULT EDUCATION/ COOPERATIVE MANAGEMENT"),
    ("ADULT EDUCATION/ LITERACY AND VOCATIONAL EDUCATION", "ADULT EDUCATION/ LITERACY AND VOCATIONAL EDUCATION"),
    ("ADULT EDUCATION/ SOCIAL DEVELOPMENT AND EXTENSION", "ADULT EDUCATION/ SOCIAL DEVELOPMENT AND EXTENSION"),
    ("AGRICULTURAL ECONOMICS", "AGRICULTURAL ECONOMICS"),
    ("AGRICULTURAL ECONOMICS AND EXTENSION SERVICES", "AGRICULTURAL ECONOMICS AND EXTENSION SERVICES"),
    ("Agricultural Economics and Extension Services (PART-TIME)", "Agricultural Economics and Extension Services (PART-TIME)"),
    ("AGRICULTURAL EXTENSION", "AGRICULTURAL EXTENSION"),
    ("Agricultural Science (DIPLOMA)", "Agricultural Science (DIPLOMA)"),
    ("AGRICULTURAL SCIENCE EDUCATION", "AGRICULTURAL SCIENCE EDUCATION"),
    ("AGRICULTURAL SCIENCE EDUCATION (SANDWICH)", "AGRICULTURAL SCIENCE EDUCATION (SANDWICH)"),
    ("ANATOMY", "ANATOMY"),
    ("Anatomy and Mortuary Laboratory Technique (DIPLOMA)", "Anatomy and Mortuary Laboratory Technique (DIPLOMA)"),
    ("ANIMAL PRODUCTION & HEALTH SCIENCES", "ANIMAL PRODUCTION & HEALTH SCIENCES"),
    ("ANIMAL SCIENCE", "ANIMAL SCIENCE"),
    ("ARABIC EDUCATION", "ARABIC EDUCATION"),
    ("ARABIC EDUCATION (SANDWICH)", "ARABIC EDUCATION (SANDWICH)"),
    ("ARABIC ISLAMIC RELIGIOUS STUDIES", "ARABIC ISLAMIC RELIGIOUS STUDIES"),
    ("ARABIC STUDIES", "ARABIC STUDIES"),
    ("ARTS AND LANGUAGE EDUCATION", "ARTS AND LANGUAGE EDUCATION"),
    ("ARTS AND LANGUAGE EDUCATION (SANDWICH)", "ARTS AND LANGUAGE EDUCATION (SANDWICH)"),
    ("Automechanics/ Metalwork TECHNOLOGY (SANDWICH)", "Automechanics/ Metalwork TECHNOLOGY (SANDWICH)"),
    ("BASIC/INTEGRATED SCI. EDUCATION (SANDWICH)", "BASIC/INTEGRATED SCI. EDUCATION (SANDWICH)"),
    ("BIOCHEMISTRY", "BIOCHEMISTRY"),
    ("BIOCHEMISTRY (SLT)", "BIOCHEMISTRY (SLT)"),
    ("BIOLOGICAL SCIENCE/ BIOTECHNOLOGY", "BIOLOGICAL SCIENCE/ BIOTECHNOLOGY"),
    ("BIOLOGY EDUCATION", "BIOLOGY EDUCATION"),
    ("BIOLOGY EDUCATION (SANDWICH)", "BIOLOGY EDUCATION (SANDWICH)"),
    ("BUILDING (SANDWICH)", "BUILDING (SANDWICH)"),
    ("BUILDING AND WOODWORK TECHNOLOGY", "BUILDING AND WOODWORK TECHNOLOGY"),
    ("BUSINESS ADMINISTRATION", "BUSINESS ADMINISTRATION"),
    ("Business Administration (DIPLOMA)", "Business Administration (DIPLOMA)"),
    ("BUSINESS ADMINISTRATION (PART-TIME)", "BUSINESS ADMINISTRATION (PART-TIME)"),
    ("BUSINESS EDUCATION", "BUSINESS EDUCATION"),
    ("BUSINESS EDUCATION (SANDWICH)", "BUSINESS EDUCATION (SANDWICH)"),
    ("BUSINESS EDUCATION/ ACCOUNTING", "BUSINESS EDUCATION/ ACCOUNTING"),
    ("BUSINESS EDUCATION/ ACCOUNTING (SANDWICH)", "BUSINESS EDUCATION/ ACCOUNTING (SANDWICH)"),
    ("BUSINESS EDUCATION/ MARKETING (SANDWICH)", "BUSINESS EDUCATION/ MARKETING (SANDWICH)"),
    ("BUSINESS EDUCATION/ OFFICE TECHNOLOGY & MANAGEMENT", "BUSINESS EDUCATION/ OFFICE TECHNOLOGY & MANAGEMENT"),
    ("BUSINESS EDUCATION/ OFFICE TECHNOLOGY & MANAGEMENT (SANDWICH)", "BUSINESS EDUCATION/ OFFICE TECHNOLOGY & MANAGEMENT (SANDWICH)"),
    ("BUSINESS EDUCATION/ SECRETARIAL (SANDWICH)", "BUSINESS EDUCATION/ SECRETARIAL (SANDWICH)"),
    ("CHEMISTRY", "CHEMISTRY"),
    ("CHEMISTRY EDUCATION", "CHEMISTRY EDUCATION"),
    ("CHEMISTRY EDUCATION (SANDWICH)", "CHEMISTRY EDUCATION (SANDWICH)"),
    ("CHEMISTRY TECHNIQUES", "CHEMISTRY TECHNIQUES"),
    ("CHILDHOOD EDUCATION", "CHILDHOOD EDUCATION"),
    ("CHILDHOOD EDUCATION (SANDWICH)", "CHILDHOOD EDUCATION (SANDWICH)"),
    ("CHRISTIAN AND RELIGIOUS STUDIES", "CHRISTIAN AND RELIGIOUS STUDIES"),
    ("CHRISTIAN AND RELIGIOUS STUDIES (PTP)", "CHRISTIAN AND RELIGIOUS STUDIES (PTP)"),
    ("CHRISTIAN RELIGION STUDIES EDUCATION", "CHRISTIAN RELIGION STUDIES EDUCATION"),
    ("CHRISTIAN RELIGION STUDIES EDUCATION (SANDWICH)", "CHRISTIAN RELIGION STUDIES EDUCATION (SANDWICH)"),
    ("CIVIL ENGINEERING", "CIVIL ENGINEERING"),
    ("Civil Engineering (DIPLOMA)", "Civil Engineering (DIPLOMA)"),
    ("Clinical Pharmacy", "Clinical Pharmacy"),
    ("COMPUTER ENGINEERING", "COMPUTER ENGINEERING"),
    ("COMPUTER SCIENCE", "COMPUTER SCIENCE"),
    ("Computer Science (PART-TIME)", "Computer Science (PART-TIME)"),
    ("Computer Science (Diploma)", "Computer Science (Diploma)"),
    ("COMPUTER SCIENCE EDUCATION", "COMPUTER SCIENCE EDUCATION"),
    ("COMPUTER SCIENCE EDUCATION (SANDWICH)", "COMPUTER SCIENCE EDUCATION (SANDWICH)"),
    ("COOPERATIVE ECONOMICS & MANAGEMENT (PART-TIME)", "COOPERATIVE ECONOMICS & MANAGEMENT (PART-TIME)"),
    ("Cooperative Studies and Rural Development", "Cooperative Studies and Rural Development"),
    ("Criminology (DIPLOMA)", "Criminology (DIPLOMA)"),
    ("CRIMINOLOGY (PART-TIME)", "CRIMINOLOGY (PART-TIME)"),
    ("CROP SCIENCE", "CROP SCIENCE"),
    ("CROP, HORTICULTURE AND LANDSCAPE", "CROP, HORTICULTURE AND LANDSCAPE"),
    ("CROP, HORTICULTURE AND LANDSCAPE DESIGN", "CROP, HORTICULTURE AND LANDSCAPE DESIGN"),
    ("CURRICULUM STUDIES", "CURRICULUM STUDIES"),
    ("CURRICULUM STUDIES (SANDWICH)", "CURRICULUM STUDIES (SANDWICH)"),
    ("DIRECTORATE OF PART-TIME", "DIRECTORATE OF PART-TIME"),
    ("ECONOMICS", "ECONOMICS"),
    ("ECONOMICS (EMT)", "ECONOMICS (EMT)"),
    ("Economics (Diploma)", "Economics (Diploma)"),
    ("ECONOMICS (PART-TIME)", "ECONOMICS (PART-TIME)"),
    ("EDUCATION (DIPLOMA)", "EDUCATION (DIPLOMA)"),
    ("EDUCATION/ ECONOMICS", "EDUCATION/ ECONOMICS"),
    ("EDUCATION/ ECONOMICS (SANDWICH)", "EDUCATION/ ECONOMICS (SANDWICH)"),
    ("EDUCATION/ GEOGRAPHY", "EDUCATION/ GEOGRAPHY"),
    ("EDUCATION/ GEOGRAPHY (SANDWICH)", "EDUCATION/ GEOGRAPHY (SANDWICH)"),
    ("EDUCATION/ POLITICAL SCIENCE", "EDUCATION/ POLITICAL SCIENCE"),
    ("EDUCATION/ POLITICAL SCIENCE (SANDWICH)", "EDUCATION/ POLITICAL SCIENCE (SANDWICH)"),
    ("EDUCATION/ SOCIAL STUDIES", "EDUCATION/ SOCIAL STUDIES"),
    ("Educational Management", "Educational Management"),
    ("EDUCATIONAL MANAGEMENT - ACCOUNTING", "EDUCATIONAL MANAGEMENT - ACCOUNTING"),
    ("EDUCATION OPTION (SANDWICH)", "EDUCATION OPTION (SANDWICH)"),
    ("EDUCATIONAL MANAGEMENT - AGRICULTURAL SCIENCE EDUCATION OPTION (SANDWICH)", "EDUCATIONAL MANAGEMENT - AGRICULTURAL SCIENCE EDUCATION OPTION (SANDWICH)"),
    ("EDUCATIONAL MANAGEMENT - BUSINESS EDUCATION OPTION (SANDWICH)", "EDUCATIONAL MANAGEMENT - BUSINESS EDUCATION OPTION (SANDWICH)"),
    ("EDUCATIONAL MANAGEMENT - CHEMISTRY EDUCATION OPTION (SANDWICH)", "EDUCATIONAL MANAGEMENT - CHEMISTRY EDUCATION OPTION (SANDWICH)"),
    ("EDUCATIONAL MANAGEMENT - ECONOMICS EDUCATION OPTION (SANDWICH)", "EDUCATIONAL MANAGEMENT - ECONOMICS EDUCATION OPTION (SANDWICH)"),
    ("EDUCATIONAL MANAGEMENT - ENGLISH EDUCATION OPTION (SANDWICH)", "EDUCATIONAL MANAGEMENT - ENGLISH EDUCATION OPTION (SANDWICH)"),
    ("EDUCATIONAL MANAGEMENT - GEOGRAPHY EDUCATION OPTION (SANDWICH)", "EDUCATIONAL MANAGEMENT - GEOGRAPHY EDUCATION OPTION (SANDWICH)"),
    ("EDUCATIONAL MANAGEMENT - MATHEMATICS EDUCATION OPTION (SANDWICH)", "EDUCATIONAL MANAGEMENT - MATHEMATICS EDUCATION OPTION (SANDWICH)"),
    ("EDUCATIONAL MANAGEMENT - POLITICAL EDUCATION OPTION (SANDWICH)", "EDUCATIONAL MANAGEMENT - POLITICAL EDUCATION OPTION (SANDWICH)"),
    ("EDUCATIONAL MANAGEMENT - SOCIAL STUDIES EDUCATION OPTION (SANDWICH)", "EDUCATIONAL MANAGEMENT - SOCIAL STUDIES EDUCATION OPTION (SANDWICH)"),
    ("EDUCATIONAL MANAGEMENT - YORUBA EDUCATION OPTION (SANDWICH)", "EDUCATIONAL MANAGEMENT - YORUBA EDUCATION OPTION (SANDWICH)"),
    ("EDUCATIONAL MANAGEMENT (ACCOUNTING)", "EDUCATIONAL MANAGEMENT (ACCOUNTING)"),
    ("Educational Management (Diploma)", "Educational Management (Diploma)"),
    ("EDUCATIONAL MANAGEMENT (ECONOMICS)", "EDUCATIONAL MANAGEMENT (ECONOMICS)"),
    ("EDUCATIONAL MANAGEMENT (GEOGRAPHY AND PLANNING SCIENCE)", "EDUCATIONAL MANAGEMENT (GEOGRAPHY AND PLANNING SCIENCE)"),
    ("EDUCATIONAL MANAGEMENT (HISTORY AND INTERNATIONAL STUDIES)", "EDUCATIONAL MANAGEMENT (HISTORY AND INTERNATIONAL STUDIES)"),
    ("EDUCATIONAL MANAGEMENT (POLITICAL SCIENCE)", "EDUCATIONAL MANAGEMENT (POLITICAL SCIENCE)"),
    ("EDUCATIONAL MANAGEMENT (SANDWICH)", "EDUCATIONAL MANAGEMENT (SANDWICH)"),
    ("EDUCATIONAL MANAGEMENT (SOCIAL STUDIES)", "EDUCATIONAL MANAGEMENT (SOCIAL STUDIES)"),
    ("EDUCATIONAL TECHNOLOGY", "EDUCATIONAL TECHNOLOGY"),
    ("EDUCATIONAL TECHNOLOGY (SANDWICH)", "EDUCATIONAL TECHNOLOGY (SANDWICH)"),
    ("ELECTRICAL & ELECTRONIC ENGINEERING", "ELECTRICAL & ELECTRONIC ENGINEERING"),
    ("Electrical and Electronic Engineering (DIPLOMA)", "Electrical and Electronic Engineering (DIPLOMA)"),
    ("ELECTRICAL ELECTRONICS (SANDWICH)", "ELECTRICAL ELECTRONICS (SANDWICH)"),
    ("ELECTRICAL ELECTRONICS", "ELECTRICAL ELECTRONICS"),
    ("ENGLISH AND LITRARY STUDIES (PART-TIME)", "ENGLISH AND LITRARY STUDIES (PART-TIME)"),
    ("ENGLISH EDUCATION", "ENGLISH EDUCATION"),
    ("ENGLISH EDUCATION (SANDWICH)", "ENGLISH EDUCATION (SANDWICH)"),
    ("ENGLISH/LITERARY STUDIES", "ENGLISH/LITERARY STUDIES"),
    ("ENTREPRENEURIAL STUDIES (PART-TIME)", "ENTREPRENEURIAL STUDIES (PART-TIME)"),
    ("ENTREPRENEURSHIP STUDIES", "ENTREPRENEURSHIP STUDIES"),
    ("ENVIRONMENTAL MANAGEMENT", "ENVIRONMENTAL MANAGEMENT"),
    ("Environmental Management (DIPLOMA)", "Environmental Management (DIPLOMA)"),
    ("ENVIRONMENTAL MANAGEMENT (PART-TIME)", "ENVIRONMENTAL MANAGEMENT (PART-TIME)"),
    ("FINANCE", "FINANCE"),
    ("FINANCE (PART-TIME)", "FINANCE (PART-TIME)"),
    ("Financial Management (DIPLOMA)", "Financial Management (DIPLOMA)"),
    ("Fine and Applied Arts (SANDWICH)", "Fine and Applied Arts (SANDWICH)"),
    ("FISHERIES AND AQUACULTURE", "FISHERIES AND AQUACULTURE"),
    ("FISHERIES AND AQUACULTURE MANAGEMENT", "FISHERIES AND AQUACULTURE MANAGEMENT"),
    ("FOOD SCIENCE AND TECHNOLOGY", "FOOD SCIENCE AND TECHNOLOGY"),
    ("FOREST RESOURCES AND WILDLIFE MANAGEMENT", "FOREST RESOURCES AND WILDLIFE MANAGEMENT"),
    ("FRENCH", "FRENCH"),
    ("FRENCH (PART-TIME)", "FRENCH (PART-TIME)"),
    ("FRENCH EDUCATION", "FRENCH EDUCATION"),
    ("FRENCH EDUCATION (Curriculum Studies)", "FRENCH EDUCATION (Curriculum Studies)"),
    ("FRENCH EDUCATION (SANDWICH)", "FRENCH EDUCATION (SANDWICH)"),
    ("Gender and Development Studies", "Gender and Development Studies"),
    ("Gender and Health Studies (DIPLOMA)", "Gender and Health Studies (DIPLOMA)"),
    ("General Management (Accounting) (DIPLOMA)", "General Management (Accounting) (DIPLOMA)"),
    ("General Management (Business Administration Option) (DIPLOMA)", "General Management (Business Administration Option) (DIPLOMA)"),
    ("General Management (DIPLOMA)", "General Management (DIPLOMA)"),
    ("GENERAL STUDIES", "GENERAL STUDIES"),
    ("GEOGRAPHY AND PLANING SCIENCE (PART-TIME)", "GEOGRAPHY AND PLANING SCIENCE (PART-TIME)"),
    ("GEOGRAPHY AND PLANNING SCIENCE", "GEOGRAPHY AND PLANNING SCIENCE"),
    ("GEOLOGY", "GEOLOGY"),
    ("GEOLOGY (APPLIED GEOPHYSICS)", "GEOLOGY (APPLIED GEOPHYSICS)"),
    ("GEOLOGY/MINING", "GEOLOGY/MINING"),
    ("GEOLOGY/MINING OPTION (SLT)", "GEOLOGY/MINING OPTION (SLT)"),
    ("GUIDANCE AND COUNSELLING", "GUIDANCE AND COUNSELLING"),
    ("GUIDANCE AND COUNSELLING (EGC)", "GUIDANCE AND COUNSELLING (EGC)"),
    ("GUIDANCE AND COUNSELLING EDUCATION - ACCOUNTING EDUCATION OPTION (SANDWICH)", "GUIDANCE AND COUNSELLING EDUCATION - ACCOUNTING EDUCATION OPTION (SANDWICH)"),
    ("GUIDANCE AND COUNSELLING EDUCATION - BIOLOGY OPTION (SANDWICH)", "GUIDANCE AND COUNSELLING EDUCATION - BIOLOGY OPTION (SANDWICH)"),
    ("GUIDANCE AND COUNSELLING EDUCATION - BUSINESS EDUCATION OPTION (SANDWICH)", "GUIDANCE AND COUNSELLING EDUCATION - BUSINESS EDUCATION OPTION (SANDWICH)"),
    ("GUIDANCE AND COUNSELLING EDUCATION - CHEMISTRY EDUCATION OPTION (SANDWICH)", "GUIDANCE AND COUNSELLING EDUCATION - CHEMISTRY EDUCATION OPTION (SANDWICH)"),
    ("GUIDANCE AND COUNSELLING EDUCATION - COMPUTER SC. OPTION (SANDWICH)", "GUIDANCE AND COUNSELLING EDUCATION - COMPUTER SC. OPTION (SANDWICH)"),
    ("GUIDANCE AND COUNSELLING EDUCATION - ECONOMICS OPTION (SANDWICH)", "GUIDANCE AND COUNSELLING EDUCATION - ECONOMICS OPTION (SANDWICH)"),
    ("GUIDANCE AND COUNSELLING EDUCATION - ENGLISH OPTION (SANDWICH)", "GUIDANCE AND COUNSELLING EDUCATION - ENGLISH OPTION (SANDWICH)"),
    ("GUIDANCE AND COUNSELLING EDUCATION - GEOGRAHY OPTION (SANDWICH)", "GUIDANCE AND COUNSELLING EDUCATION - GEOGRAHY OPTION (SANDWICH)"),
    ("GUIDANCE AND COUNSELLING EDUCATION - HEALTH EDUCATION OPTION (SANDWICH)", "GUIDANCE AND COUNSELLING EDUCATION - HEALTH EDUCATION OPTION (SANDWICH)"),
    ("GUIDANCE AND COUNSELLING EDUCATION - INTEGRATED OPTION (SANDWICH)", "GUIDANCE AND COUNSELLING EDUCATION - INTEGRATED OPTION (SANDWICH)"),
    ("GUIDANCE AND COUNSELLING EDUCATION - POLITICAL OPTION (SANDWICH)", "GUIDANCE AND COUNSELLING EDUCATION - POLITICAL OPTION (SANDWICH)"),
    ("GUIDANCE AND COUNSELLING EDUCATION - SOCIAL STUDIES OPTION (SANDWICH)", "GUIDANCE AND COUNSELLING EDUCATION - SOCIAL STUDIES OPTION (SANDWICH)"),
    ("GUIDANCE AND COUNSELLING EDUCATION (SANDWICH)", "GUIDANCE AND COUNSELLING EDUCATION (SANDWICH)"),
    ("HEALTH EDUCATION", "HEALTH EDUCATION"),
    ("HEALTH EDUCATION (SANDWICH)", "HEALTH EDUCATION (SANDWICH)"),
    ("HISTORY AND INTERNATIONAL STUDIES", "HISTORY AND INTERNATIONAL STUDIES"),
    ("HISTORY AND INTERNATIONAL STUDIES (PART-TIME)", "HISTORY AND INTERNATIONAL STUDIES (PART-TIME)"),
    ("HISTORY EDUCATION", "HISTORY EDUCATION"),
    ("HISTORY EDUCATION (SANDWICH)", "HISTORY EDUCATION (SANDWICH)"),
    ("Home Economics (SANDWICH)", "Home Economics (SANDWICH)"),
    ("HORTICULTURE AND LANDSCAPE MANAGEMENT", "HORTICULTURE AND LANDSCAPE MANAGEMENT"),
    ("HUMAN KINETICS EDUCATION", "HUMAN KINETICS EDUCATION"),
    ("INDUSTRIAL CHEMISTRY", "INDUSTRIAL CHEMISTRY"),
    ("INDUSTRIAL RELATION & PERSONNEL (PART-TIME)", "INDUSTRIAL RELATION & PERSONNEL (PART-TIME)"),
    ("INDUSTRIAL RELATIONS AND PERSONNEL MANAGEMENT", "INDUSTRIAL RELATIONS AND PERSONNEL MANAGEMENT"),
    ("Information Technology (Diploma)", "Information Technology (Diploma)"),
    ("INSURANCE", "INSURANCE"),
    ("INSURANCE (PART-TIME)", "INSURANCE (PART-TIME)"),
    ("INTEGRATED SCI. EDUCATION", "INTEGRATED SCI. EDUCATION"),
    ("INTEGRATED SCIENCE", "INTEGRATED SCIENCE"),
    ("INTELLIGENCE AND SECURITY STUDIES", "INTELLIGENCE AND SECURITY STUDIES"),
    ("INTELLIGENCE AND SECURITY STUDIES (PTP)", "INTELLIGENCE AND SECURITY STUDIES (PTP)"),
    ("INTERNATIONAL RELATIONS", "INTERNATIONAL RELATIONS"),
    ("INTERNATIONAL RELATIONS (PTP)", "INTERNATIONAL RELATIONS (PTP)"),
    ("ISLAMIC STUDIES", "ISLAMIC STUDIES"),
    ("Islamic Studies (sandwich)", "Islamic Studies (sandwich)"),
    ("JUPEB SCIENCE DEPARTMENT", "JUPEB SCIENCE DEPARTMENT"),
    ("JUPEB NON SCIENCE DEPARTMENT", "JUPEB NON SCIENCE DEPARTMENT"),
    ("KINETIC AND HEALTH EDUCATION (DIPLOMA)", "KINETIC AND HEALTH EDUCATION (DIPLOMA)"),
    ("KINETIC AND HEALTH EDUCATION (SANDWICH)", "KINETIC AND HEALTH EDUCATION (SANDWICH)"),
    ("LAW", "LAW"),
    ("LAW (DIPLOMA)", "LAW (DIPLOMA)"),
    ("LIBRARY AND INFORMATION SCIENCE", "LIBRARY AND INFORMATION SCIENCE"),
    ("LIBRARY AND INFORMATION SCIENCE (SANDWICH)", "LIBRARY AND INFORMATION SCIENCE (SANDWICH)"),
    ("LINGUISTICS AND NIGERIAN LANGUAGES", "LINGUISTICS AND NIGERIAN LANGUAGES"),
    ("Management (Diploma)", "Management (Diploma)"),
    ("MARKETING", "MARKETING"),
    ("MARKETING (PART-TIME)", "MARKETING (PART-TIME)"),
    ("MASS COMMUNICATION", "MASS COMMUNICATION"),
    ("Mass Communication (Diploma)", "Mass Communication (Diploma)"),
    ("MASS COMMUNICATION (PTP)", "MASS COMMUNICATION (PTP)"),
    ("MATHEMATICS", "MATHEMATICS"),
    ("MATHEMATICS (PART-TIME)", "MATHEMATICS (PART-TIME)"),
    ("MATHEMATICS EDUCATION", "MATHEMATICS EDUCATION"),
    ("MATHEMATICS EDUCATION (sandwich)", "MATHEMATICS EDUCATION (sandwich)"),
    ("MECHANICAL ENGINEERING", "MECHANICAL ENGINEERING"),
    ("MECHANICAL TECHNOLOGY (METAL/ AUTOMECHANICS)", "MECHANICAL TECHNOLOGY (METAL/ AUTOMECHANICS)"),
    ("MECHANICAL TECHNOLOGY (SANDWICH)", "MECHANICAL TECHNOLOGY (SANDWICH)"),
    ("MECHATRONICS ENGINEERING", "MECHATRONICS ENGINEERING"),
    ("MED", "MED"),
    ("MEDICAL BIOCHEMISTRY", "MEDICAL BIOCHEMISTRY"),
    ("MEDICAL LABORATORY SCIENCE", "MEDICAL LABORATORY SCIENCE"),
    ("MEDICINE AND SURGERY", "MEDICINE AND SURGERY"),
    ("MICROBIOLOGY", "MICROBIOLOGY"),
    ("Microbiology (Diploma)", "Microbiology (Diploma)"),
    ("Music (SANDWICH)", "Music (SANDWICH)"),
    ("NURSERY AND PRIMARY EDUCATION", "NURSERY AND PRIMARY EDUCATION"),
    ("NURSERY AND PRIMARY EDUCATION (SANDWICH)", "NURSERY AND PRIMARY EDUCATION (SANDWICH)"),
    ("NURSING SCIENCE", "NURSING SCIENCE"),
    ("Peace and Conflict Resolution", "Peace and Conflict Resolution"),
    ("Peace and Conflict Resolution (PTP)", "Peace and Conflict Resolution (PTP)"),
    ("Peace, Security and Governance (DIPLOMA)", "Peace, Security and Governance (DIPLOMA)"),
    ("PHARMACEUTICAL MICROBIOLOGY & BIOTECHNOLOGY", "PHARMACEUTICAL MICROBIOLOGY & BIOTECHNOLOGY"),
    ("Pharmaceutical Technology", "Pharmaceutical Technology"),
    ("Pharmacognosy", "Pharmacognosy"),
    ("Pharmacy", "Pharmacy"),
    ("PHILOSOPHY", "PHILOSOPHY"),
    ("PHILOSOPHY (PART-TIME)", "PHILOSOPHY (PART-TIME)"),
    ("PHYSICS", "PHYSICS"),
    ("PHYSICS EDUCATION", "PHYSICS EDUCATION"),
    ("PHYSICS EDUCATION (Curriculum Studies)", "PHYSICS EDUCATION (Curriculum Studies)"),
    ("PHYSICS EDUCATION (SANDWICH)", "PHYSICS EDUCATION (SANDWICH)"),
    ("PHYSICS/ELECTRONICS", "PHYSICS/ELECTRONICS"),
    ("PHYSIOLOGY", "PHYSIOLOGY"),
    ("PLANT SCIENCES", "PLANT SCIENCES"),
    ("PLANT SCIENCES AND BIOTECHNOLOGY", "PLANT SCIENCES AND BIOTECHNOLOGY"),
    ("POLITICAL SCIENCE", "POLITICAL SCIENCE"),
    ("POLITICAL SCIENCE (EMT)", "POLITICAL SCIENCE (EMT)"),
    ("Political Science (DIPLOMA)", "Political Science (DIPLOMA)"),
    ("POLITICAL SCIENCE (PART-TIME)", "POLITICAL SCIENCE (PART-TIME)"),
    ("PSYCHOLOGY AND BEHAVIOURAL STUDIES", "PSYCHOLOGY AND BEHAVIOURAL STUDIES"),
    ("PSYCHOLOGY AND BEHAVIOURAL STUDIES (PART-TIME)", "PSYCHOLOGY AND BEHAVIOURAL STUDIES (PART-TIME)"),
    ("Public Administration", "Public Administration"),
    ("Public Administration (DIPLOMA)", "Public Administration (DIPLOMA)"),
    ("PUBLIC ADMINISTRATION (PART-TIME)", "PUBLIC ADMINISTRATION (PART-TIME)"),
    ("Religious (Diploma)", "Religious (Diploma)"),
    ("RELIGIOUS STUDIES", "RELIGIOUS STUDIES"),
    ("RELIGIOUS STUDIES (PART-TIME)", "RELIGIOUS STUDIES (PART-TIME)"),
    ("Religious Studies (SANDWICH)", "Religious Studies (SANDWICH)"),
    ("SCIENCE EDUCATION", "SCIENCE EDUCATION"),
    ("SCIENCE EDUCATION (SANDWICH)", "SCIENCE EDUCATION (SANDWICH)"),
    ("SCIENCE LABOATORY TECHNOLOGY", "SCIENCE LABOATORY TECHNOLOGY"),
    ("SCIENCE LABORATORY TECHNOLOGY - BIOCHEMISTRY OPTION (SLT PART-TIME)", "SCIENCE LABORATORY TECHNOLOGY - BIOCHEMISTRY OPTION (SLT PART-TIME)"),
    ("SCIENCE LABORATORY TECHNOLOGY - BIOTECH OPTION (SLT PART-TIME)", "SCIENCE LABORATORY TECHNOLOGY - BIOTECH OPTION (SLT PART-TIME)"),
    ("SCIENCE LABORATORY TECHNOLOGY - CHEMISTRY OPTION (SLT PART-TIME)", "SCIENCE LABORATORY TECHNOLOGY - CHEMISTRY OPTION (SLT PART-TIME)"),
    ("SCIENCE LABORATORY TECHNOLOGY - GEOLOGY OPTION (SLT PART-TIME)", "SCIENCE LABORATORY TECHNOLOGY - GEOLOGY OPTION (SLT PART-TIME)"),
    ("SCIENCE LABORATORY TECHNOLOGY - MICROBIOLOGY OPTION (SLT PART-TIME)", "SCIENCE LABORATORY TECHNOLOGY - MICROBIOLOGY OPTION (SLT PART-TIME)"),
    ("SCIENCE LABORATORY TECHNOLOGY - PHYSICS OPTION (SLT PART-TIME)", "SCIENCE LABORATORY TECHNOLOGY - PHYSICS OPTION (SLT PART-TIME)"),
    ("Science Laboratory Technology (DIPLOMA)", "Science Laboratory Technology (DIPLOMA)"),
    ("SCIENCE LABORATORY TECHNOLOGY (SLT PART-TIME)", "SCIENCE LABORATORY TECHNOLOGY (SLT PART-TIME)"),
    ("Social Pharmacy & Pharmacy Administration", "Social Pharmacy & Pharmacy Administration"),
    ("SOCIAL SCIENCE EDUCATION (SANDWICH)", "SOCIAL SCIENCE EDUCATION (SANDWICH)"),
    ("SOCIAL STUDIES (EMT)", "SOCIAL STUDIES (EMT)"),
    ("SOCIAL STUDIES EDUCATION (SANDWICH)", "SOCIAL STUDIES EDUCATION (SANDWICH)"),
    ("Social Work", "Social Work"),
    ("Social Work (Diploma)", "Social Work (Diploma)"),
    ("Social Work (PTP)", "Social Work (PTP)"),
    ("SOCIOLOGY", "SOCIOLOGY"),
    ("Sociology (DIPLOMA)", "Sociology (DIPLOMA)"),
    ("SOCIOLOGY (PART-TIME)", "SOCIOLOGY (PART-TIME)"),
    ("SOIL RESOURCES AND ENVIRONMENTAL MANAGEMENT", "SOIL RESOURCES AND ENVIRONMENTAL MANAGEMENT"),
    ("STATISTICS", "STATISTICS"),
    ("Statistics (Diploma)", "Statistics (Diploma)"),
    ("STATISTICS (PART-TIME)", "STATISTICS (PART-TIME)"),
    ("TECHNICAL EDUCATION", "TECHNICAL EDUCATION"),
    ("TECHNICAL EDUCATION (SANDWICH)", "TECHNICAL EDUCATION (SANDWICH)"),
    ("TEST, MEASUREMENT AND EVALUATION", "TEST, MEASUREMENT AND EVALUATION"),
    ("THEATRE AND MEDIA ARTS", "THEATRE AND MEDIA ARTS"),
    ("Theatre and Media Arts (DIPLOMA)", "Theatre and Media Arts (DIPLOMA)"),
    ("Theatre and Media Arts (PTP)", "Theatre and Media Arts (PTP)"),
    ("TOURISM STUDIES", "TOURISM STUDIES"),
    ("TOURISM STUDIES (PART-TIME)", "TOURISM STUDIES (PART-TIME)"),
    ("VOCATION AND TECHNICAL EDUCATION (SANDWICH)", "VOCATION AND TECHNICAL EDUCATION (SANDWICH)"),
    ("VOCATIONAL AND TECHNICAL EDUCATION", "VOCATIONAL AND TECHNICAL EDUCATION"),
    ("YORUBA", "YORUBA"),
    ("YORUBA EDUCATION", "YORUBA EDUCATION"),
    ("YORUBA EDUCATION (SANDWICH)", "YORUBA EDUCATION (SANDWICH)"),
    ("ZOOLOGY", "ZOOLOGY"),
    ("ZOOLOGY AND ENVIRONMENTAL BIOLOGY", "ZOOLOGY AND ENVIRONMENTAL BIOLOGY"),
]


class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    remember = BooleanField("Remember me")


class RegisterForm(FlaskForm):
    full_name = StringField("Full name", validators=[DataRequired(), Length(min=2, max=120)])
    email = StringField("Email", validators=[DataRequired(), Email(), Length(max=120)])
    department = SelectField("Department", choices=DEPARTMENTS, validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired(), Length(min=8)])
    confirm_password = PasswordField(
        "Confirm password", validators=[DataRequired(), EqualTo("password", message="Passwords must match")]
    )


class ChangePasswordForm(FlaskForm):
    current_password = PasswordField("Current password", validators=[DataRequired()])
    new_password = PasswordField("New password", validators=[DataRequired(), Length(min=8)])
    confirm_new_password = PasswordField(
        "Confirm new password", validators=[DataRequired(), EqualTo("new_password", message="Passwords must match")]
    )


class ProfileForm(FlaskForm):
    full_name = StringField("Full name", validators=[DataRequired(), Length(min=2, max=120)])
    email = StringField("Email", validators=[DataRequired(), Email(), Length(max=120)])
    department = SelectField("Department", choices=DEPARTMENTS, validators=[Optional()])


class SubmitChapterForm(FlaskForm):
    chapter_numbers = SelectMultipleField(
        "Chapters", choices=[(str(i), f"Chapter {i}") for i in range(1, 6)],
        validators=[DataRequired()],
    )
    notes = TextAreaField("Notes (optional)", validators=[Optional(), Length(max=1000)])
    file = FileField("Chapter PDF", validators=[FileRequired(), FileAllowed(["pdf"], "PDF files only")])


class ResubmitChapterForm(FlaskForm):
    file = FileField("Updated PDF", validators=[FileRequired(), FileAllowed(["pdf"], "PDF files only")])


class ReviewSubmissionForm(FlaskForm):
    overall_comment = TextAreaField("Overall feedback", validators=[Optional(), Length(max=2000)])
    decision = HiddenField("Decision", validators=[DataRequired()])


class UserForm(FlaskForm):
    full_name = StringField("Full name", validators=[DataRequired(), Length(min=2, max=120)])
    email = StringField("Email", validators=[DataRequired(), Email(), Length(max=120)])
    department = SelectField("Department", choices=DEPARTMENTS, validators=[Optional()])
    role = SelectField("Role", choices=[("student", "Student"), ("supervisor", "Supervisor")],
                        validators=[DataRequired()])
    password = PasswordField("Password", validators=[Optional(), Length(min=8)])
    is_active = BooleanField("Active", default=True)


class AssignSupervisorForm(FlaskForm):
    student_id = SelectField("Student", coerce=int, validators=[DataRequired()])
    supervisor_id = SelectField("Supervisor", coerce=int, validators=[DataRequired()])


class DeadlineForm(FlaskForm):
    chapter_number = IntegerField("Chapter number", validators=[DataRequired(), NumberRange(min=1, max=10)])
    due_date = DateField("Due date", validators=[DataRequired()])


class BroadcastForm(FlaskForm):
    target = SelectField(
        "Send to", choices=[("students", "All Students"), ("supervisors", "All Supervisors"), ("everyone", "Everyone")],
        validators=[DataRequired()],
    )
    message = TextAreaField("Message", validators=[DataRequired(), Length(max=500)])


MEETING_DURATIONS = [
    (30, "30 minutes"),
    (45, "45 minutes"),
    (60, "1 hour"),
    (90, "1.5 hours"),
    (120, "2 hours"),
]


class ScheduleMeetingForm(FlaskForm):
    title = StringField("Meeting Title", validators=[DataRequired(), Length(max=200)])
    description = TextAreaField("Message / Agenda", validators=[Optional(), Length(max=1000)])
    platform = SelectField(
        "Platform",
        choices=[("google_meet", "Google Meet"), ("zoom", "Zoom")],
        validators=[DataRequired()],
    )
    zoom_email = StringField(
        "Your Zoom Email",
        validators=[Optional(), Email(), Length(max=120)],
    )
    google_email = StringField(
        "Your Google Email",
        validators=[Optional(), Email(), Length(max=120)],
    )
    meeting_link = StringField("Google Meet Link", validators=[Optional(), Length(max=500)])
    date = DateField("Date", validators=[DataRequired()])
    time = TimeField("Time", format="%H:%M", validators=[DataRequired()])
    duration = SelectField(
        "Duration",
        choices=MEETING_DURATIONS,
        coerce=int,
        validators=[DataRequired()],
    )
